# Simple workflow for deploying static content to GitHub Pages
name: Deploy   Docker container 
on:
  pull_request:
    branches:
      - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  packages: write

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: self-hosted
    steps:
      - name: test run docker
        run: docker run hello-world